### ISSUE TITLE
Unable to change network/chainId on local

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1104]
<img width="1680" alt="Screenshot 2022-12-17 at 9 48 29 AM" src="https://user-images.githubusercontent.com/93455288/208247617-0d9e686d-f182-4b4a-8a3f-7d718abb3f20.png">

**Comment by FlacoJones** [comment]
This is from a completely unconnected Wallet. Then i connected my wallet, was on Polygon Mainnet, clicked this and got this error

**Comment by Monseceaser** [comment]
Talk to Polygon Support on the [POA Live Support](https://forumpoa.network/I/-/l/main.html#) so that your issue can be looked into.

**Comment by Christopher-Stevers** [comment]
I'm getting it as well. Could this be an issue with how are local chain is working - this switch chain function is working fine on staging.

**Comment by ArcAnya** [comment]
Agree with @Christopher-Stevers - it works on staging but seems to run into issues. My understanding is still limited, but wondering if that's because of the following (cf the first point about origin allowlist?):
https://docs.metamask.io/guide/rpc-api.html#wallet-addethereumchain

![image](https://user-images.githubusercontent.com/75732239/212886352-f206b5c5-940d-4ee2-bf78-dc14d9d1ee32.png)
