### ISSUE TITLE
"Connect wallet" shown on ClaimButton when already connected, also Claim button should lead user to the Requirements walkthrough

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1309]
Noticed this after selecting self as winner

I also think that rather than being fully disabled, the Claim button on the submissions page should lead the user to their profile where they can fulfill all the requirements

<img width="667" alt="Screenshot 2023-02-11 at 11 41 26 AM" src="https://user-images.githubusercontent.com/93455288/218272833-ee0d3ade-fb2b-49f4-8564-35a201c3e0ea.png">

**Comment by ArcAnya** [comment]
Actually, the message was probably accurate, since it's not the wallet connect message showing here but the one related to the "associating your github profile to wallet" => but it can sound confusing so I will rephrase that so it gets clearer

Agreed on the second part - but rather than the user profile I would suggest sending them on the ClaimPage where, in my opinion, the flow of requirements to fulfill for a specific bounty is clearer (if that's OK)
