### ISSUE TITLE
For associateAddressToExternalId, show associated address even if its only Github but no wallet connected

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1345]
I noticed on staging that we only show that an address is associated after the user has connected that wallet.

Is it possible to do this the other way around? with GithubID -> Wallet?

Do we have the data available such that, with no Wallet but Github signed in, we can show that the person has an associated address?

I think we don't on the Graph, but we do on the contract if you call the mapping `externalUserIdToAddress`. Could use this.

I think people who are logged in with Github but not with wallet (most people actually since the oauth token lasts a month) will feel flustered if we say "no wallet connected"

**Comment by ArcAnya** [comment]
Had a look but actually I had already changed to using `externalUserIdToAddress` since we have our login all around Github accounts now 

If I see it correctly, the pb is that in order to interact with that method of our contract we need "library" & "signer" - hence the user needs to be somehow connected (but it doesn't need to be the right wallet, just to be connected with any account) to be able to receive that info - correct?

So I'm guessing, if the above is correct, the best would be adding sthg to our Graph?
