### ISSUE TITLE
After minting KYC i got a weird scroll bar under the nav bar

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1549]
<img width="1009" alt="Screenshot 2023-03-03 at 3 43 05 PM" src="https://user-images.githubusercontent.com/93455288/222845458-2454bc44-ddf6-4e81-bb8a-918c89eb66a4.png">

**Comment by ArcAnya** [comment]
That's due to the fact that when you validate KYC, there is the additional "checkmark icon" that appears - when more of those appear, the length of the Submenu is too long and it becomes a scrollbar

If we want to change this at that point I would suggest positioning the Profile image lower and using the full length of the screen for the Submenu?

**Comment by FlacoJones** [comment]
Ya lets do that
