### ISSUE TITLE
Still getting spammy WalletConnect errors in console

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1586]
<img width="928" alt="Screenshot 2023-03-05 at 4 07 40 PM" src="https://user-images.githubusercontent.com/93455288/222991202-ea8bcea8-b2b7-48f0-80f2-f8b5cb7608af.png">

**Comment by Christopher-Stevers** [comment]
What page are you getting this on?

**Comment by Christopher-Stevers** [comment]
![image](https://user-images.githubusercontent.com/72156679/223218024-d1fa7b7e-d604-4ae7-90cd-f10e9b5535eb.png)
this is what I'm getting in staging when connected via wallet connect - I'm still don't know if its worth debugging any of the wallet connect stuff, since its should upgraded to v2 soon.

**Comment by ArcAnya** [comment]
I tried to fix it by limiting the use of "new WalletConnectProvider" in useWeb3() to the Kyc page - and it reduced it BUT I'm also seeing it happen randomly at times on local (sometimes just on the homepage, or when i jump around tabs on the contract view) - was trying to track it / fix it yesterday when I was seeing it but so far not successful

Haven't seen it on staging anymore - but maybe because I'm more on local since Sunday
