### ISSUE TITLE
Add a prompt to add email in first signup modal

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1605]
I'm realizing how important it is that we get users to associate their email as early as possible.

We really want to encourage them to add email ASAP, so after they login in with their Github, we should prompt them like so:

"Hello [GITHUB NAME!] 

If you're coming here as an EthDenver Buidlathon winner, congratulations!

Let's get you paid.

Enter your email to stay up to date with next steps in claiming your award.

OpenQ and EthDenver will use this email to tell you when you uploaded forms have been approved, after which you can claim right away."

**Comment by FlacoJones** [comment]
Under which we can have a big alluring green "Submit", and one of those greyed out "Skip for Now >" text buttons to discourage clicking it

**Comment by FlacoJones** [comment]
Once we get this, we could even send reminders and such if they take like 4 weeks to upload their tax docs for example.

**Comment by ArcAnya** [comment]
in PR #1621 
So far it looks like this. Did not add the "skip for now" since it's in the FirstSignupModal flow. Or did you want a different modal that pops up first? Or for just this to show and onClick of Submit/Skip for now we see the next question about the participants?

![image](https://user-images.githubusercontent.com/75732239/223982022-cd0df80e-0a98-4326-a965-d90fe1c0947c.png)
