### ISSUE TITLE
Lock budget to 1.00 USDC price same as we've done for TVL

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#1715]
It looks like we've locked USDC price for funded bounties, like this: https://openq.dev/contract/I_kwDOI-Vpys5fRUOh/0x028fc6dc697ff3b5bc0a18a27e17b5bdfa9b515b

But we also want to do the same for unfunded, only Budgeted bounties, like this: https://openq.dev/contract/I_kwDOI-Vpys5hLEIP/0x0ee99d53dc95a26d197b324a7ad7a8a8422ab433

I believe Chris achieved this by manually setting the token price to 1.00 instead of the usual 0.9999 and such it returns as, but can't confirm

**Comment by ArcAnya** [comment]
It seems to me that the issue is not a USDC conversion one but just that the Budget it a sum of the Payout Schedule - which runs into rounding issues when 3 winners share 1 tier prize (diving a multiple of 10 by 3) - that's why for instance this issue is fine:

![image](https://user-images.githubusercontent.com/75732239/228182901-7692df8c-c666-4bd2-b185-7be6b021b3f0.png)

While this one is not:

![image](https://user-images.githubusercontent.com/75732239/228183028-53251f85-c475-4131-bfc4-2eee56a4f981.png)

I'll see if I can improve that with rounding / precision somehow

**Comment by ArcAnya** [comment]
Confirmed:
![image](https://user-images.githubusercontent.com/75732239/228186930-f97d2753-270b-4399-a65e-46e52eee0729.png)
