### ISSUE TITLE
Lock the Total Value Claimed to the price of the assets at time of Claim

### ISSUE THREAD

**Issue by FlacoJones** [OpenQDev/OpenQ-Frontend#187]

**Comment by FlacoJones** [comment]
A bounty has been minted for this issue at https://app.openq.dev/bounty/I_kwDOGAqhQc5HIWPm/0x6f31C17f7ff482ba6ab9EB0CAf1576dae711aac3

**Comment by ArcAnya** [comment]
A few considerations:
- makes sense in ActionBubbles (claim value), Claimoverview (maybe adding a column "value at time of Claim"), and in any historical data we will want to show for us (e.g. dashboard) or to users, otherwise actual nbs will be distorted (to the upside or downside)
- maybe the same should be done for the fund values (e.g. in the ActionBubbles and any stat we want to show when an bounty is closed)

Question:
- do we want to store the data somewhere or calculate on the go based off historical price data?

**Comment by ArcAnya** [comment]
@alo9507 how should we go about the calculation of the values at claim time on contest and split price (we'll need both value at claim & current value probably)?

Token-Price-CronJob => stop updating value for claimed amounts

**Comment by ArcAnya** [comment]
API Udpate to get it into contract object
