### ISSUE TITLE
Claim page still available after repeatable contract is closed.

### ISSUE THREAD

**Issue by Christopher-Stevers** [OpenQDev/OpenQ-Frontend#648]

**Comment by ArcAnya** [comment]
Do you mean we should get rid of the Claim Tab altogether? On my end, after closing the repeatable contract the ClaimPage is still there but with the BountyClosed message so that the claim interface is not there anymore.

In general I agree that there should be a better concept on what to show (same goes for FundPage/RefundPage/Admin Tab) when a bounty is closed or claimed.

**Comment by Christopher-Stevers** [comment]
Hmm, I may need to look into it more. This is what I'm seeing:
![image](https://user-images.githubusercontent.com/72156679/186229392-8c786648-329b-452e-975e-5c516369f160.png)
I might have gotten something wrong here with merging.

**Comment by Christopher-Stevers** [comment]
My bad, sounds like I was missing graph updates.
